---
- name: Copy weekly scan job template
  template: src=weekly_rhel_scan.yaml.j2 dest={{ ansible_env.HOME}}/weekly_rhel_scan.yaml
  become: true
  tags: weeklyscan

- name: Configure job for weekly scan in jenkins
  shell: "jenkins-jobs --ignore-cache update {{ ansible_env.HOME}}/weekly_rhel_scan.yaml"
  become: true
